local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"
local _constants = require('lollo_lorry_station/constants')
local moduleHelpers = require('lollo_lorry_station.moduleHelpers')

function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	cost = {
		price = 24000,
	},
	category = {
		categories = { "cargo", },
	},
	description = {
		name = _("Cargo links, 4 x 4 m"),
		description = _("Links for waiting cargo, 4 x 4 m, collision free. Place them across obstacles to connect more cargo areas."),
		icon = "ui/construction/station/street/cargo_links_4x4.tga"
	},
	metadata = {
		cargo = true,
	},
	order = {
		value = 8,
	},
	type = _constants.cargoLinks4x4ModuleType,
	updateFn = function(result, transform, tag, slotId, addModelFn, params, callback)
        local x, y, baseId = result.demangleId(slotId)
		if not x or not y or not baseId then return end

		-- print('LOLLO cargo_links_4x4 module received slotId, x, y, baseId = ', slotId, x, y, baseId)
		-- print('LOLLO result =')
		-- debugPrint(result)

		-- addModelFn(_constants.cargoLinks4x4ModelFileName, transf.transl(vec3.new(0, 0, 0)), modelTag)
		result.models[#result.models + 1] = {
			id = _constants.cargoLinks4x4ModelFileName,
			slotId = slotId,
			transf = transform,
			tag = _constants.cargoLinks4x4ModelTag
		}
	end,

	getModelsFn = function()
		return {
			{
				id = _constants.cargoLinksEnhanced4x4ModelFileName,
				transf = transf.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
