local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"
local _constants = require('lollo_lorry_station/constants')

function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	cost = {
		price = 24000,
	},
	category = {
		categories = { "cargo", },
	},
	description = {
		name = _("Cargo area with gravel, 5 x 5 m"),
		description = _("Area for waiting cargo, 5 x 5 m, with gravel."),
		icon = "ui/construction/station/street/platform_cargo.tga"
	},
	metadata = {
		cargo = true,
	},
	order = {
		value = 7,
	},
	type = _constants.cargoAreaInner5x5ModuleType,
	updateFn = function(result, transform, tag, slotId, addModelFn, params, callback)
        local x, y, baseId = result.DemangleId(slotId)
		if not x or not y or not baseId then return end

		-- print('LOLLO small cargo area module received slotId, x, y, baseId = ', slotId, x, y, baseId)
		-- print('LOLLO result =')
		-- debugPrint(result)

		-- addModelFn(_constants.cargoAreaInner5x5ModelFileName, transf.transl(vec3.new(0, 0, 0)), modelTag)
		result.models[#result.models + 1] = {
			id = 'lollo_lorry_station/cargo_area_inner_5x5_gravel.mdl', --_constants.cargoAreaInner5x5ModelFileName,
			slotId = slotId,
			transf = transform,
			tag = _constants.cargoAreaInner5x5ModelTag
		}

		local faces = {
			{-3.5, -3.5, 0, 1},
			{-3.5, 3.5, 0, 1},
			{3.5, 3.5, 0, 1},
			{3.5, -3.5, 0, 1},
		}
		modulesutil.TransformFaces(transform, faces)
		result.groundFaces[#result.groundFaces + 1] = {
			face = faces,
			loop = true,
			modes = {
				{
					type = 'FILL',
					key = 'shared/gravel_03.gtex.lua' -- 'asphalt_like_street.lua', -- 'shared/asphalt_01.gtex.lua' --'shared/gravel_03.gtex.lua'
				}
			}
		}

		-- if not result.coord2terminalInfo[tostring(x)] then
		-- 	result.coord2terminalInfo[tostring(x)] = {}
		-- end
		-- result.coord2terminalInfo[tostring(x)][tostring(y)] = {
		-- 	model = #result.models - 1,
		-- 	terminal = 0
		-- }
	end,

	getModelsFn = function()
		return {
			{
				id = 'lollo_lorry_station/cargo_area_inner_5x5_gravel.mdl', --_constants.cargoAreaInner5x5ModelFileName,
				transf = transf.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
