local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"
local _constants = require('lollo_lorry_station/constants')

function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	cost = {
		price = 24000,
	},
	category = {
		categories = { "cargo", },
	},
	description = {
		name = _("Cargo area with gravel, 15 x 15 m"),
		description = _("Area for waiting cargo, 15 x 15 m, with gravel."),
		icon = "ui/construction/station/street/platform_cargo.tga"
	},
	metadata = {
		cargo = true,
	},
	order = {
		value = 7,
	},
	type = _constants.cargoAreaInner15x15ModuleType,
	updateFn = function(result, transform, tag, slotId, addModelFn, params, callback)
        local x, y, baseId = result.DemangleId(slotId)
		if not x or not y or not baseId then return end

		-- print('LOLLO cargo area module received slotId, x, y, baseId = ', slotId, x, y, baseId)
		-- print('LOLLO result =')
		-- debugPrint(result)

		-- addModelFn(_constants.cargoAreaInner15x15ModelFileName, transf.transl(vec3.new(0, 0, 0)), modelTag)
		result.models[#result.models + 1] = {
			id = 'lollo_lorry_station/cargo_area_inner_15x15_gravel.mdl', --_constants.cargoAreaInner15x15ModelFileName,
			slotId = slotId,
			transf = transform,
			tag = _constants.cargoAreaInner15x15ModelTag
		}

		-- if params.modules[result.MangleId({x, right and y + 1 or y - 1, 1})] == nil then
		-- 	addModelFn("station/road/streetstation/" .. result.erastr .. "cargo_pltfrm_r_top.mdl", transf.rotZTransl(right and 0 or math.pi, vec3.new(.0, .0, .0)))
		-- end
		-- if params.modules[result.MangleId({x, right and y - 1 or y + 1, 1})] == nil then
		-- 	addModelFn("station/road/streetstation/" .. result.erastr .. "cargo_pltfrm_r_btm.mdl", transf.rotZTransl(right and 0 or math.pi, vec3.new(.0, .0, .0)))
		-- end

		-- addModelFn("station/road/streetstation/" .. result.erastr .. "cargo_path_rep" .. result.cat .. ".mdl", transf.rotZTransl(right and 0 or math.pi, vec3.new(right and -7.5 or 7.5, .0, .0)))
		-- result.coord2terminalInfo[x][y] = {
		-- 	model = #result.models - 1,
		-- 	terminal = 0,
		-- }

		local faces = {
			{-8.5, -8.5, 0, 1},
			{-8.5, 8.5, 0, 1},
			{8.5, 8.5, 0, 1},
			{8.5, -8.5, 0, 1},
		}
		modulesutil.TransformFaces(transform, faces)
		result.groundFaces[#result.groundFaces + 1] = {
			face = faces,
			loop = true,
			modes = {
				{
					type = 'FILL',
					key = 'shared/gravel_03.gtex.lua' -- 'asphalt_like_street.lua', -- 'shared/asphalt_01.gtex.lua' --'shared/gravel_03.gtex.lua'
				}
			}
		}

		-- if not result.coord2terminalInfo[tostring(x)] then
		-- 	result.coord2terminalInfo[tostring(x)] = {}
		-- end
		-- result.coord2terminalInfo[tostring(x)][tostring(y)] = {
		-- 	model = #result.models - 1,
		-- 	terminal = 0
		-- }
	end,

	getModelsFn = function(params)
		return {
			{
				id = 'lollo_lorry_station/cargo_area_inner_15x15_gravel.mdl',
				transf = transf.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
