local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"
local _constants = require('lollo_lorry_station/constants')
local moduleHelpers = require('lollo_lorry_station.moduleHelpers')

function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	cost = {
		price = 24000,
	},
	category = {
		categories = { "cargo", },
	},
	description = {
		name = _("Cargo area with earth, 4 x 4 m"),
		description = _("Area for waiting cargo, 4 x 4 m, with earth."),
		icon = "ui/construction/station/street/cargo_area_inner_4x4_earth.tga"
	},
	metadata = {
		cargo = true,
	},
	order = {
		value = 7,
	},
	type = _constants.cargoAreaInner4x4ModuleType,
	updateFn = function(result, transform, tag, slotId, addModelFn, params, callback)
        local x, y, baseId = result.demangleId(slotId)
		if not x or not y or not baseId then return end

		-- print('LOLLO small cargo area module received slotId, x, y, baseId = ', slotId, x, y, baseId)
		-- print('LOLLO result =')
		-- debugPrint(result)
-- LOLLO TODO try addModelFn
		-- addModelFn(_constants.cargoAreaInner4x4ModelFileName, transf.transl(vec3.new(0, 0, 0)), modelTag)
		result.models[#result.models + 1] = {
			id = 'lollo_lorry_station/cargo_area_inner_4x4_earth.mdl', --_constants.cargoAreaInner4x4ModelFileName,
			slotId = slotId,
			transf = transform,
			tag = _constants.cargoAreaInner4x4ModelTag
		}

		local face = {
			{-3, -3, 0, 1},
			{-3, 3, 0, 1},
			{3, 3, 0, 1},
			{3, -3, 0, 1},
		}
		modulesutil.TransformFaces(transform, face)
		result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(face, 'shared/dirt.gtex.lua')
		result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = moduleHelpers.getTerrainAlignmentList(face)
		-- if not result.coord2terminalInfo[tostring(x)] then
		-- 	result.coord2terminalInfo[tostring(x)] = {}
		-- end
		-- result.coord2terminalInfo[tostring(x)][tostring(y)] = {
		-- 	model = #result.models - 1,
		-- 	terminal = 0
		-- }
	end,
-- LOLLO TODO test colliders

	getModelsFn = function()
		-- LOLLO TODO across the app, make elements easy to remove, even if they are slightly under the ground
		-- maybe use dedicated models with something tall on these getModelsFn's ? Nope.
		-- or maybe use the same models but raise them? Nope.
		-- or maybe use height? Nope.
		-- or maybe reintroduce a mesh? That's the only way.
		-- For now there is a low concrete track and roofs, but somehow nothing turns yellow when bulldozing a module.
		-- Only the streetside modules turn yellow. Some modules turn yellow, then you add some more modules and
		-- they don't turn yellow anymore. Either it's a bug or an undocumented "feature".
		return {
			{
				id = 'lollo_lorry_station/cargo_area_inner_4x4_earth.mdl', --_constants.cargoAreaInner4x4ModelFileName,
				-- id = 'lollo_lorry_station/cargo_area_inner_4x4_visual_aid.mdl', --_constants.cargoAreaInner4x4ModelFileName,
				transf = transf.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
