local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"
local edgeUtils = require('lollo_lorry_station/edgeHelpers')
local _constants = require('lollo_lorry_station/constants')

function data()

return { 
	cost = {
		price = 24000,
	},
	category = {
		categories = { "cargo", },
	},
	description = {
		name = _("Lollo cargo path"),
		description = _("Lollo platform for waiting cargo."),
		icon = "ui/construction/station/street/platform_cargo.tga"
	}, 
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	type = "lollo_street_terminal_lorry_bay",
	order = {
		value = 6,
	},
	metadata = {
		cargo = true,
	},
	
	updateFn = function(result, transform, tag, slotId, addModelFn, params)
        local x, y, baseId = result.DemangleId(slotId)
		if not x or not y or not baseId then return end

		print('LOLLO slotId, x, y, baseId = ', slotId, x, y, baseId)

		addModelFn("lollo_models/lollo_lorry_bay.mdl", transf.transl(vec3.new(.0, .0, .0)), _constants.lorryBayTag)
		
		-- if params.modules[result.MangleId({x, right and y + 1 or y - 1, 1})] == nil then
		-- 	addModelFn("station/road/streetstation/" .. result.erastr .. "cargo_pltfrm_r_top.mdl", transf.rotZTransl(right and 0 or math.pi, vec3.new(.0, .0, .0)))
		-- end
		-- if params.modules[result.MangleId({x, right and y - 1 or y + 1, 1})] == nil then
		-- 	addModelFn("station/road/streetstation/" .. result.erastr .. "cargo_pltfrm_r_btm.mdl", transf.rotZTransl(right and 0 or math.pi, vec3.new(.0, .0, .0)))
		-- end
		
		-- addModelFn("station/road/streetstation/" .. result.erastr .. "cargo_path_rep" .. result.cat .. ".mdl", transf.rotZTransl(right and 0 or math.pi, vec3.new(right and -7.5 or 7.5, .0, .0)))
		-- result.coord2terminalInfo[x][y] = {
		-- 	model = #result.models - 1,
		-- 	terminal = 0,
		-- }
		if not result.coord2terminalInfo[edgeUtils.getXKey(x)] then result.coord2terminalInfo[edgeUtils.getXKey(x)] = {} end
		print('LOLLO setting coord2TerminalInfo in cargo path module, x = ', edgeUtils.getXKey(x), ' and y = ', edgeUtils.getYKey(y))
		result.coord2terminalInfo[edgeUtils.getXKey(x)][edgeUtils.getYKey(y)] = {
			model = #result.models - 1,
			terminal = 0
		}
	end,
	
	getModelsFn = function()
		
		local result = {
			{
				id = "lollo_models/lollo_lorry_bay.mdl",
				transf = transf.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
		
		return result
	end
}

end
