local transfUtilsUG = require "transf"
local vec3 = require "vec3"
local _constants = require('lollo_lorry_station/constants')

function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		cost = {
			price = 0,
		},
		category = {
			categories = { "cargo", },
		},
		description = {
			name = _("Remove All"),
			description = _("Remove all rebuilding the road"),
			-- icon = "ui/button/small/bulldoze.tga"
			-- icon = "ui/button/small/bulldoze@2x.tga"
			-- icon = "ui/button/large/bulldozer.tga"
			-- icon = "ui/icons/game-menu/bulldozer@2x.tga"
			icon = "ui/construction/lollo_lorry_station/remove-all.tga"
		},
		metadata = {
			cargo = true,
		},
		order = {
			value = 0,
		},
		type = _constants.removeAllModuleType,
		updateFn = function(result, transform, tag, slotId, addModelFn, params, callback)
			local x, y, baseId = result.demangleId(slotId)
			print('removeAll placed, x =', x, ', y =', y, ', baseId =', baseId)
			-- if not x or not y or not baseId then return end
		end,

		getModelsFn = function()
			return {}
			-- return {
			-- 	{
			-- 		id = 'lollo_lorry_station/cargo_area_inner_4x4_earth.mdl', --_constants.cargoAreaInner4x4ModelFileName,
			-- 		transf = transfUtilsUG.transl(vec3.new(0.0, 0.0, 0.0)),
			-- 	},
			-- }
		end
	}
end
