local constants = require('lollo_lorry_station.constants')
local logger = require('lollo_lorry_station.logger')
local slotHelpers = require('lollo_lorry_station.slotHelpers')

function data()
	return {
		availability = {
			yearFrom = -1,
			yearTo = -1
		},
		cost = {
			price = 0,
		},
		category = {
			categories = { "cargo", },
		},
		description = {
			name = _("dummyName"),
			description = _("dummyDesc"),
			icon = "ui/construction/lollo_lorry_station/store-cargo-on-pavement@2x.tga"
		},
		metadata = {
			-- cargo = true,
		},
		order = {
			value = 99,
		},
		type = constants.dummyModuleType,
		updateFn = function(result, transform, tag, slotId, addModelFn, params, updateScriptParams)
			local x, y, baseId = slotHelpers.demangleId(slotId)
			logger.print('dummy placed, x =', x, ', y =', y, ', baseId =', baseId)
			-- if not x or not y or not baseId then return end
		end,

		getModelsFn = function()
			return {}
		end
	}
end
