local modulesutil = require "modulesutil"
local constants = require('lollo_lorry_station.constants')
local moduleHelpers = require('lollo_lorry_station.moduleHelpers')
local slotHelpers = require('lollo_lorry_station.slotHelpers')
local transfUtils = require('lollo_lorry_station.transfUtils')

function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		cost = {
			price = 24000,
		},
		category = {
			categories = { "cargo", },
		},
		description = {
			name = _("Cargo area with gravel, 4 x 4 m"),
			description = _("Area for waiting cargo, 4 x 4 m, with gravel. Toggle the roof with <m> and <n>. Repaint the ground with <shift>."),
			icon = "ui/construction/lollo_lorry_station/cargo_area_inner_4x4_gravel.tga"
		},
		metadata = {
			cargo = true,
			moreCapacity = {
				cargo = 4,
				passenger = 0
			},
		},
		order = {
			value = 22,
		},
		type = constants.cargoAreaInner4x4ModuleType,
		updateFn = function(result, transform, tag, slotId, addModelFn, params, updateScriptParams)
			local x, y, baseId = slotHelpers.demangleId(slotId)
			if not x or not y or not baseId then return end

			if (moduleHelpers.getVariant(params, slotId) % 2 == 0) then
				result.models[#result.models + 1] = {
					id = 'lollo_lorry_station/cargo_area_inner_roof_4x4.mdl',
					slotId = slotId,
					transf = transfUtils.position2Transf(transfUtils.transf2Position(transform)),
					tag = tag
				}
			end
			result.models[#result.models + 1] = {
				id = 'lollo_lorry_station/cargo_area_inner_4x4_gravel_no_roof.mdl',
				slotId = slotId,
				transf = transform,
				tag = tag
			}
			result.models[#result.models + 1] = {
				id = 'lollo_lorry_station/cargo_area_inner_4x4_lanes.mdl',
				slotId = slotId,
				transf = transform,
				tag = constants.modelWithCargoAreaTag -- custom tag, so the main model won't turn yellow when configuring, which models do when they contain lanes
			}

			slotHelpers.updateSlotIdsWithModule(slotId, result)

			local face = {
				{-3, -3, 0, 1},
				{-3, 3, 0, 1},
				{3, 3, 0, 1},
				{3, -3, 0, 1},
			}
			modulesutil.TransformFaces(transform, face)
			result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(face, 'shared/gravel_03.gtex.lua')
			result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = moduleHelpers.getTerrainAlignmentList(face)
		end,

		getModelsFn = function()
			return {
				{
					id = 'lollo_lorry_station/cargo_area_inner_4x4_gravel.mdl',
					transf = constants.idTransf,
				},
			}
		end
	}
end
