local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local _constants = require('lollo_lorry_station.constants')
local moduleHelpers = require('lollo_lorry_station.moduleHelpers')

function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	cost = {
		price = 24000,
	},
	category = {
		categories = { "cargo", },
	},
	description = {
		name = _("Streetside cargo area, no roof, no tarmac"),
		description = _("Streetside area for waiting cargo, no roof, no tarmac. Repaint the ground with or without <shift>."),
		icon = "ui/construction/lollo_lorry_station/cargo_area_streetside_12x4_invisible.tga"
	},
	metadata = {
		cargo = true,
	},
	order = {
		value = 12,
	},
	type = _constants.cargoAreaStreetside12x4ModuleType,
	updateFn = function(result, transform, tag, slotId, addModelFn, params, callback)
        local x, y, baseId = result.demangleId(slotId)
		if not x or not y or not baseId then return end

		result.models[#result.models + 1] = {
			id = 'lollo_lorry_station/cargo_area_streetside_12x4_invisible.mdl',
			slotId = slotId,
			transf = transform,
			tag = tag
		}

		local face = {
			{-7, -2.5, 0, 1},
			{-7, 2.5, 0, 1},
			{7, 2.5, 0, 1},
			{7, -2.5, 0, 1},
		}
		modulesutil.TransformFaces(transform, face)
		result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(face, 'shared/asphalt_01.gtex.lua')
		result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = moduleHelpers.getTerrainAlignmentList(face)
	end,

	getModelsFn = function()
		return {
			{
				id = 'lollo_lorry_station/cargo_area_streetside_12x4_no_roof.mdl',
				transf = transf.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
