local transfUtilsUG = require "transf"
local vec3 = require "vec3"
local constants = require('lollo_lorry_station.constants')
local logger = require('lollo_lorry_station.logger')

function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		cost = {
			price = 0,
		},
		category = {
			categories = { "cargo", },
		},
		description = {
			name = _("isStoreCargoOnPavementName"),
			description = _("isStoreCargoOnPavementDesc"),
			icon = "ui/construction/lollo_lorry_station/store-cargo-on-pavement.tga"
		},
		metadata = {
			cargo = true,
		},
		order = {
			value = 2,
		},
		type = constants.storeCargoOnPavementModuleType,
		updateFn = function(result, transform, tag, slotId, addModelFn, params, callback)
			local x, y, baseId = result.demangleId(slotId)
			logger.print('storeCargoOnPavement placed, x =', x, ', y =', y, ', baseId =', baseId)
			-- if not x or not y or not baseId then return end
		end,

		getModelsFn = function()
			return {}
			-- return {
			-- 	{
			-- 		id = 'lollo_lorry_station/cargo_area_inner_4x4_earth.mdl',
			-- 		transf = transfUtilsUG.transl(vec3.new(0.0, 0.0, 0.0)),
			-- 	},
			-- }
		end
	}
end
