local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local constructionutil = require "constructionutil"
local _constants = require('lollo_lorry_station.constants')
local moduleHelpers = require('lollo_lorry_station.moduleHelpers')

function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	cost = {
		price = 24000,
	},
	category = {
		categories = { "cargo", },
	},
	description = {
		name = _("Streetside cargo area"),
		description = _("Streetside area for waiting cargo."),
		icon = "ui/construction/lollo_lorry_station/cargo_area_streetside_15x5.tga"
	},
	metadata = {
		cargo = true,
	},
	order = {
		value = 7,
	},
	type = _constants.cargoAreaStreetside15x5ModuleType,
	updateFn = function(result, transform, tag, slotId, addModelFn, params, callback)
        local x, y, baseId = result.demangleId(slotId)
		if not x or not y or not baseId then return end

		-- print('LOLLO streetside cargo area module received slotId, x, y, baseId = ', slotId, x, y, baseId)
		-- print('LOLLO result =')
		-- debugPrint(result)

		-- addModelFn(_constants.cargoAreaStreetside15x5ModelFileName, transf.transl(vec3.new(0, 0, 0)), modelTag)
		result.models[#result.models + 1] = {
			id = _constants.cargoAreaStreetside15x5ModelFileName,
			slotId = slotId,
			transf = transform,
			tag = tag
		}

		local face = {
			{-8.5, -2.5, 0, 1},
			{-8.5, 3, 0, 1},
			{8.5, 3, 0, 1},
			{8.5, -2.5, 0, 1},
		}
		modulesutil.TransformFaces(transform, face)
		result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(face, 'shared/asphalt_01.gtex.lua')
		result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = moduleHelpers.getTerrainAlignmentList(face)
		-- if not result.coord2terminalInfo[tostring(x)] then
		-- 	result.coord2terminalInfo[tostring(x)] = {}
		-- end
		-- result.coord2terminalInfo[tostring(x)][tostring(y)] = {
		-- 	model = #result.models - 1,
		-- 	terminal = 0
		-- }
	end,

	getModelsFn = function()
		return {
			{
				id = _constants.cargoAreaStreetside15x5ModelFileName,
				transf = transf.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
