local constants = require('lollo_lorry_station.constants')
local logger = require('lollo_lorry_station.logger')
local slotHelpers = require('lollo_lorry_station.slotHelpers')

function data()
	return {
		availability = {
			yearFrom = 0,
			yearTo = 0
		},
		cost = {
			price = 0,
		},
		category = {
			categories = { "cargo", },
		},
		description = {
			name = _("removeModulesName"),
			description = _("removeModulesDesc"),
			icon = "ui/construction/lollo_lorry_station/remove-modules.tga"
		},
		metadata = {
			-- cargo = true,
		},
		order = {
			value = 95,
		},
		type = constants.removeModulesModuleType,
		updateFn = function(result, transform, tag, slotId, addModelFn, params, updateScriptParams)
			local x, y, baseId = slotHelpers.demangleId(slotId)
			logger.print('removeModules placed, x =', x, ', y =', y, ', baseId =', baseId)
			-- if not x or not y or not baseId then return end
		end,

		getModelsFn = function()
			return {}
		end
	}
end
