local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local _constants = require('lollo_lorry_station/constants')
local moduleHelpers = require('lollo_lorry_station.moduleHelpers')

function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	cost = {
		price = 24000,
	},
	category = {
		categories = { "cargo", },
	},
	description = {
		name = _("Cargo links, 5 x 5 m"),
		description = _("Links for waiting cargo, 5 x 5 m, invisible and collision free. Place them across obstacles to connect separate cargo areas."),
		icon = "ui/construction/lollo_lorry_station/cargo_links_5x5.tga"
	},
	metadata = {
		cargo = true,
	},
	order = {
		value = 8,
	},
	type = _constants.cargoLinks5x5ModuleType,
	updateFn = function(result, transform, tag, slotId, addModelFn, params, callback)
        local x, y, baseId = result.demangleId(slotId)
		if not x or not y or not baseId then return end

		result.models[#result.models + 1] = {
			id = _constants.cargoLinks5x5ModelFileName,
			slotId = slotId,
			transf = transform,
			tag = tag
		}
	end,

	getModelsFn = function()
		return {
			{
				id = _constants.cargoLinks5x5ModelFileName,
				transf = transf.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
