local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local _constants = require('lollo_lorry_station.constants')
local moduleHelpers = require('lollo_lorry_station.moduleHelpers')

function data()

return {
	availability = {
		yearFrom = 0,
		yearTo = 0
	},
	cost = {
		price = 24000,
	},
	category = {
		categories = { "cargo", },
	},
	description = {
		name = _("Cargo area with earth, 4 x 4 m"),
		description = _("Area for waiting cargo, 4 x 4 m, with earth. Toggle the roof with <m> and <n>. Repaint the ground with <shift>."),
		icon = "ui/construction/lollo_lorry_station/cargo_area_inner_4x4_earth.tga"
	},
	metadata = {
		cargo = true,
		moreCapacity = {
			cargo = 4,
			passenger = 0
		}
	},
	order = {
		value = 24,
	},
	type = _constants.cargoAreaInner4x4ModuleType,
	updateFn = function(result, transform, tag, slotId, addModelFn, params, callback)
        local x, y, baseId = result.demangleId(slotId)
		if not x or not y or not baseId then return end

		-- LOLLO NOTE tag looks like __module_121309, base_config.lua writes it.
		-- set the model tags to it to have them turn yellow when configuring

		local modelId = (moduleHelpers.getVariant(params, slotId) >= 0)
			and 'lollo_lorry_station/cargo_area_inner_4x4_earth.mdl'
			or 'lollo_lorry_station/cargo_area_inner_4x4_earth_no_roof.mdl'
		result.models[#result.models + 1] = {
			id = modelId,
			slotId = slotId,
			transf = transform,
			tag = tag
		}

		local face = {
			{-3, -3, 0, 1},
			{-3, 3, 0, 1},
			{3, 3, 0, 1},
			{3, -3, 0, 1},
		}
		modulesutil.TransformFaces(transform, face)
		result.groundFaces[#result.groundFaces + 1] = moduleHelpers.getGroundFace(face, 'shared/dirt.gtex.lua')
		result.terrainAlignmentLists[#result.terrainAlignmentLists + 1] = moduleHelpers.getTerrainAlignmentList(face)
		-- if not result.coord2terminalInfo[tostring(x)] then
		-- 	result.coord2terminalInfo[tostring(x)] = {}
		-- end
		-- result.coord2terminalInfo[tostring(x)][tostring(y)] = {
		-- 	model = #result.models - 1,
		-- 	terminal = 0
		-- }
	end,

	getModelsFn = function()
		return {
			{
				id = 'lollo_lorry_station/cargo_area_inner_4x4_earth.mdl',
				transf = transf.transl(vec3.new(0.0, 0.0, 0.0)),
			},
		}
	end
}

end
