return {
  {
    categories = { "country", },
    fileName = "standard/country_x_large_new.lua",
    icon = "ui/streets/standard/country_x_large_new.tga",
    isAllTramTracks = false,
    laneCount = 8,
    name = "Extra-large country road",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 24,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "country", },
    fileName = "lollo_x_large_6_tram_tracks_country_road.lua",
    icon = "ui/streets/lollo_x_large_6_tram_tracks_country_road.tga",
    isAllTramTracks = true,
    laneCount = 8,
    name = "Extra-large country road - 6 lanes - 6 tram tracks",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 24,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "urban", },
    fileName = "standard/town_x_large_new.lua",
    icon = "ui/streets/standard/town_x_large_new.tga",
    isAllTramTracks = false,
    laneCount = 8,
    name = "Extra-large street",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 24,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "urban", },
    fileName = "lollo_x_large_6_tram_tracks_street.lua",
    icon = "ui/streets/lollo_x_large_6_tram_tracks_street.tga",
    isAllTramTracks = true,
    laneCount = 8,
    name = "Extra-large street - 6 tram tracks",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 24,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "highway", },
    fileName = "standard/country_small_one_way_new.lua",
    icon = "ui/streets/standard/country_small_one_way_new.tga",
    isAllTramTracks = false,
    laneCount = 3,
    name = "Highway ramp",
    rightLaneWidth = 3,
    sidewalkWidth = 3,
    streetWidth = 3,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "country", },
    fileName = "standard/country_large_new.lua",
    icon = "ui/streets/standard/country_large_new.tga",
    isAllTramTracks = false,
    laneCount = 6,
    name = "Large country road",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 16,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "country", },
    fileName = "lollo_large_4_lane_4_tram_tracks_country_road.lua",
    icon = "ui/streets/lollo_large_4_lane_4_tram_tracks_country_road.tga",
    isAllTramTracks = true,
    laneCount = 6,
    name = "Large country road - 4 tram tracks",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 16,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "country", },
    fileName = "lollo_large_6_lane_country_road.lua",
    icon = "ui/streets/lollo_large_6_lane_country_road.tga",
    isAllTramTracks = false,
    laneCount = 8,
    name = "Large country road - 6 lanes",
    rightLaneWidth = 3.3333332538605,
    sidewalkWidth = 2,
    streetWidth = 20,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "country", },
    fileName = "lollo_large_6_lane_6_tram_tracks_country_road.lua",
    icon = "ui/streets/lollo_large_6_lane_6_tram_tracks_country_road.tga",
    isAllTramTracks = true,
    laneCount = 8,
    name = "Large country road - 6 lanes - 6 tram tracks",
    rightLaneWidth = 3.3333332538605,
    sidewalkWidth = 2,
    streetWidth = 20,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "highway", },
    fileName = "standard/country_large_one_way_new.lua",
    icon = "ui/streets/standard/country_large_one_way_new.tga",
    isAllTramTracks = false,
    laneCount = 5,
    name = "Large highway",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 12,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "highway", },
    fileName = "lollo_large_1_way_3_lane_3_tram_tracks_country_road.lua",
    icon = "ui/streets/lollo_large_1_way_3_lane_3_tram_tracks_country_road.tga",
    isAllTramTracks = true,
    laneCount = 5,
    name = "Large highway - 3 lanes - 3 tram tracks",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 12,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "standard/town_large_one_way_new.lua",
    icon = "ui/streets/standard/town_large_one_way_new.tga",
    isAllTramTracks = false,
    laneCount = 5,
    name = "Large one-way street",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 12,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "lollo_large_1_way_3_lane_3_tram_tracks_street.lua",
    icon = "ui/streets/lollo_large_1_way_3_lane_3_tram_tracks_street.tga",
    isAllTramTracks = true,
    laneCount = 5,
    name = "Large one-way street - 3 tram tracks",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 12,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "urban", },
    fileName = "standard/town_large_new.lua",
    icon = "ui/streets/standard/town_large_new.tga",
    isAllTramTracks = false,
    laneCount = 6,
    name = "Large street",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 16,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "urban", },
    fileName = "lollo_large_4_lane_4_tram_tracks_street.lua",
    icon = "ui/streets/lollo_large_4_lane_4_tram_tracks_street.tga",
    isAllTramTracks = true,
    laneCount = 6,
    name = "Large street - 4 tram tracks",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 16,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "urban", },
    fileName = "lollo_large_6_lane_street.lua",
    icon = "ui/streets/lollo_large_6_lane_street.tga",
    isAllTramTracks = false,
    laneCount = 8,
    name = "Large street - 6 lanes",
    rightLaneWidth = 3.3333332538605,
    sidewalkWidth = 2,
    streetWidth = 20,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "urban", },
    fileName = "lollo_large_6_lane_6_tram_tracks_street.lua",
    icon = "ui/streets/lollo_large_6_lane_6_tram_tracks_street.tga",
    isAllTramTracks = true,
    laneCount = 8,
    name = "Large street - 6 lanes - 6 tram tracks",
    rightLaneWidth = 3.3333332538605,
    sidewalkWidth = 2,
    streetWidth = 20,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "country", },
    fileName = "standard/country_medium_new.lua",
    icon = "ui/streets/standard/country_medium_new.tga",
    isAllTramTracks = false,
    laneCount = 4,
    name = "Medium country road",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 8,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "country", },
    fileName = "lollo_medium_4_lane_country_road.lua",
    icon = "ui/streets/lollo_medium_4_lane_country_road.tga",
    isAllTramTracks = false,
    laneCount = 6,
    name = "Medium country road - 4 lanes",
    rightLaneWidth = 3,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "country", },
    fileName = "lollo_medium_4_lane_4_tram_tracks_country_road.lua",
    icon = "ui/streets/lollo_medium_4_lane_4_tram_tracks_country_road.tga",
    isAllTramTracks = true,
    laneCount = 6,
    name = "Medium country road - 4 lanes - 4 tram tracks",
    rightLaneWidth = 3,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "highway", },
    fileName = "standard/country_medium_one_way_new.lua",
    icon = "ui/streets/standard/country_medium_one_way_new.tga",
    isAllTramTracks = false,
    laneCount = 4,
    name = "Medium highway",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 8,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "highway", },
    fileName = "lollo_medium_1_way_2_lane_2_tram_tracks_country_road.lua",
    icon = "ui/streets/lollo_medium_1_way_2_lane_2_tram_tracks_country_road.tga",
    isAllTramTracks = true,
    laneCount = 4,
    name = "Medium highway - 2 tram tracks",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 8,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "highway", },
    fileName = "lollo_medium_1_way_3_lane_country_road.lua",
    icon = "ui/streets/lollo_medium_1_way_3_lane_country_road.tga",
    isAllTramTracks = false,
    laneCount = 5,
    name = "Medium highway - 3 lanes",
    rightLaneWidth = 4,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "highway", },
    fileName = "lollo_medium_1_way_3_lane_3_tram_tracks_country_road.lua",
    icon = "ui/streets/lollo_medium_1_way_3_lane_3_tram_tracks_country_road.tga",
    isAllTramTracks = true,
    laneCount = 5,
    name = "Medium highway - 3 tram tracks",
    rightLaneWidth = 4,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "standard/town_medium_one_way_new.lua",
    icon = "ui/streets/standard/town_medium_one_way_new.tga",
    isAllTramTracks = false,
    laneCount = 4,
    name = "Medium one-way street",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 8,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "lollo_medium_1_way_2_lane_2_tram_tracks_street.lua",
    icon = "ui/streets/lollo_medium_1_way_2_lane_2_tram_tracks_street.tga",
    isAllTramTracks = true,
    laneCount = 4,
    name = "Medium one-way street - 2 tram tracks",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 8,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "lollo_medium_1_way_2_lane_2_tram_tracks_medium_sidewalk_street.lua",
    icon = "ui/streets/lollo_medium_1_way_2_lane_2_tram_tracks_medium_sidewalk_street.tga",
    isAllTramTracks = true,
    laneCount = 4,
    name = "Medium one-way street - 2 tram tracks - 2m pavement",
    rightLaneWidth = 6,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "lollo_medium_1_way_2_lane_medium_sidewalk_street.lua",
    icon = "ui/streets/lollo_medium_1_way_2_lane_medium_sidewalk_street.tga",
    isAllTramTracks = false,
    laneCount = 4,
    name = "Medium one-way street - 2m pavement",
    rightLaneWidth = 6,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "lollo_medium_1_way_3_lane_street.lua",
    icon = "ui/streets/lollo_medium_1_way_3_lane_street.tga",
    isAllTramTracks = false,
    laneCount = 5,
    name = "Medium one-way street - 3 lanes",
    rightLaneWidth = 4,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "lollo_medium_1_way_3_lane_3_tram_tracks_street.lua",
    icon = "ui/streets/lollo_medium_1_way_3_lane_3_tram_tracks_street.tga",
    isAllTramTracks = true,
    laneCount = 5,
    name = "Medium one-way street - 3 lanes - 3 tram tracks",
    rightLaneWidth = 4,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "lollo_medium_1_way_4_lane_street.lua",
    icon = "ui/streets/lollo_medium_1_way_4_lane_street.tga",
    isAllTramTracks = false,
    laneCount = 6,
    name = "Medium one-way street - 4 lanes",
    rightLaneWidth = 3,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "lollo_medium_1_way_4_lane_4_tram_tracks_street.lua",
    icon = "ui/streets/lollo_medium_1_way_4_lane_4_tram_tracks_street.tga",
    isAllTramTracks = true,
    laneCount = 6,
    name = "Medium one-way street - 4 lanes - 4 tram tracks",
    rightLaneWidth = 3,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "urban", },
    fileName = "standard/town_medium_new.lua",
    icon = "ui/streets/standard/town_medium_new.tga",
    isAllTramTracks = false,
    laneCount = 4,
    name = "Medium street",
    rightLaneWidth = 4,
    sidewalkWidth = 4,
    streetWidth = 8,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "urban", },
    fileName = "lollo_medium_2_lane_medium_sidewalk_street.lua",
    icon = "ui/streets/lollo_medium_2_lane_medium_sidewalk_street.tga",
    isAllTramTracks = false,
    laneCount = 4,
    name = "Medium street - 2m pavement",
    rightLaneWidth = 6,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "urban", },
    fileName = "lollo_medium_4_lane_street.lua",
    icon = "ui/streets/lollo_medium_4_lane_street.tga",
    isAllTramTracks = false,
    laneCount = 6,
    name = "Medium street - 4 lanes",
    rightLaneWidth = 3,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "urban", },
    fileName = "lollo_medium_4_lane_4_tram_tracks_street.lua",
    icon = "ui/streets/lollo_medium_4_lane_4_tram_tracks_street.tga",
    isAllTramTracks = true,
    laneCount = 6,
    name = "Medium street - 4 lanes - 4 tram tracks",
    rightLaneWidth = 3,
    sidewalkWidth = 2,
    streetWidth = 12,
    aiLock = true,
    yearTo = 0,
  },
  {
    categories = { "highway", },
    fileName = "lollo_medium_1_way_1_lane_country_road_narrow_sidewalk.lua",
    icon = "ui/streets/lollo_medium_1_way_1_lane_country_road_narrow_sidewalk.tga",
    isAllTramTracks = false,
    laneCount = 3,
    name = "Narrow one-way road - 1 lane - .8 m shoulder",
    rightLaneWidth = 2.4000000953674,
    sidewalkWidth = 0.80000001192093,
    streetWidth = 2.4000000953674,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "lollo_medium_1_way_1_lane_street.lua",
    icon = "ui/streets/lollo_medium_1_way_1_lane_street.tga",
    isAllTramTracks = false,
    laneCount = 3,
    name = "Narrow one-way street - 1 lane",
    rightLaneWidth = 4,
    sidewalkWidth = 2,
    streetWidth = 4,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "lollo_medium_1_way_1_lane_street_narrow_sidewalk.lua",
    icon = "ui/streets/lollo_medium_1_way_1_lane_street_narrow_sidewalk.tga",
    isAllTramTracks = false,
    laneCount = 3,
    name = "Narrow one-way street - 1 lane - .8 m pavement",
    rightLaneWidth = 2.4000000953674,
    sidewalkWidth = 0.80000001192093,
    streetWidth = 2.4000000953674,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "country", },
    fileName = "standard/country_small_new.lua",
    icon = "ui/streets/standard/country_small_new.tga",
    isAllTramTracks = false,
    laneCount = 4,
    name = "Small country road",
    rightLaneWidth = 3,
    sidewalkWidth = 3,
    streetWidth = 6,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "one-way", },
    fileName = "standard/town_small_one_way_new.lua",
    icon = "ui/streets/standard/town_small_one_way_new.tga",
    isAllTramTracks = false,
    laneCount = 3,
    name = "Small one-way street",
    rightLaneWidth = 3,
    sidewalkWidth = 3,
    streetWidth = 3,
    aiLock = false,
    yearTo = 0,
  },
  {
    categories = { "urban", },
    fileName = "standard/town_small_new.lua",
    icon = "ui/streets/standard/town_small_new.tga",
    isAllTramTracks = false,
    laneCount = 4,
    name = "Small street",
    rightLaneWidth = 3,
    sidewalkWidth = 3,
    streetWidth = 6,
    aiLock = false,
    yearTo = 0,
  },
}
